-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 16:53:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lacalle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lacalle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lacalle` DEFAULT CHARACTER SET utf8 ;
USE `lacalle` ;

-- -----------------------------------------------------
-- Table `lacalle`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacalle`.`producto` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(75) NOT NULL,
  `precio` DECIMAL(5,2) NOT NULL,
  `cantidadPorUnidad` DECIMAL(5,2) NOT NULL,
  `unidadDeMedida` VARCHAR(2) NOT NULL,
  `tipoProducto` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacalle`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacalle`.`restaurante` (
  `cif` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `codigoRestaurante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoRestaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacalle`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacalle`.`usuario` (
  `nombre` VARCHAR(15) NOT NULL,
  `contraseña` VARCHAR(500) NOT NULL,
  `Restaurante_codigoRestaurante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`, `Restaurante_codigoRestaurante`),
  INDEX `fk_Usuario_Restaurante1_idx` (`Restaurante_codigoRestaurante` ASC) ,
  CONSTRAINT `fk_Usuario_Restaurante1`
    FOREIGN KEY (`Restaurante_codigoRestaurante`)
    REFERENCES `lacalle`.`restaurante` (`codigoRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacalle`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacalle`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Usuario_usuario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedido_Usuario1_idx` (`Usuario_usuario` ASC) ,
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`Usuario_usuario`)
    REFERENCES `lacalle`.`usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacalle`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacalle`.`administrador` (
  `nombre` VARCHAR(12) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`nombre`, `contraseña`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacalle`.`productospedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacalle`.`productospedidos` (
  `producto_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  `cantidad` INT NULL,
  `lote` VARCHAR(25) NULL,
  PRIMARY KEY (`producto_id`, `pedido_id`),
  INDEX `fk_producto_has_pedido_pedido1_idx` (`pedido_id` ASC) ,
  INDEX `fk_producto_has_pedido_producto1_idx` (`producto_id` ASC) ,
  CONSTRAINT `fk_producto_has_pedido_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `lacalle`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `lacalle`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
